packages:
  - packages/*

catalog:
  vite: ^6.2.1
  turbo: ^2.4.4
  vue: ^2.6.14
  axios: ^1.7.7
  core-js: ^3.38.1
  eslint: ^7.32.0
  eslint-config-prettier: ^8.3.0
  eslint-plugin-prettier: ^5.1.3
  eslint-plugin-vue: ^8.0.3
  install: ^0.13.0
  less: ^4.2.0
  less-loader: ^12.2.0
  svg-sprite-loader: ^6.0.11
  vue-template-compiler: ^2.6.14
  autoprefixer: ^10.4.16
  prettier: ^3.2.2
  prettier-plugin-tailwindcss: ^0.5.11
  github-markdown-css: ^5.8.1
  postcss: ^8.4.33
  clsx: ^2.1.1
  tailwindcss: ^3.4.1
  tailwind-merge: ^3.2.0
  markdown-it: ^14.1.0
  markdown-it-emoji: ^3.0.0
  markdown-it-abbr: ^2.0.0
  markdown-it-deflist: ^3.0.0
  markdown-it-footnote: ^4.0.0
  markdown-it-ins: ^4.0.0
  markdown-it-mark: ^4.0.0
  markdown-it-task-lists: ^2.1.1
  markdown-it-toc-done-right: ^4.2.0
  markdown-it-link-attributes: ^4.0.1
  "@babel/core": ^7.12.16
  "@babel/eslint-parser": ^7.12.16
  "@vue/cli-plugin-babel": ~5.0.0
  "@vue/cli-plugin-eslint": ~5.0.0
  "@vue/cli-service": ~5.0.0
  "@21tb/tbc-sse": ^0.0.6
  
